In [ ]:
import numpy as np
list1 = [1, 2, 3, 4, 5]
print(np.array(list1))

[1 2 3 4 5]


In [ ]:
list2 = np.arange(2, 11).reshape(3, 3)
print(list2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
list1 = np.zeros(10)
list1[5] = 11
print(list1)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [ ]:
list3 = np.arange(12,38)
print(list3)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
list4 = np.array([1, 2, 3, 4, 5])
list4 = list4.astype(float)
print(list4)

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
fahrenheit = np.array([0, 12, 45.21, 34, 99.91, 32])
celsius = np.round((fahrenheit - 32) * (5/9), 2)
print("Values in Fahrenheit degrees:", fahrenheit)
print("Values in Centigrade degrees:", celsius)


Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30])
arr = np.append(arr, [40, 50, 60, 70, 80, 90])
print(arr)

[10 20 30 40 50 60 70 80 90]


In [ ]:
import numpy as np
array = np.random.randint(1, 100, 10)
mean = np.mean(array)
median = np.median(array)
std = np.std(array)
print(array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)

[32 72 45 30 68 27 93 69 90 44]
Mean: 57.0
Median: 56.5
Standard Deviation: 23.32809465001375


In [ ]:
import numpy as np
ar = np.random.rand(10, 10)
ar = np.round(ar, 2) 
print(ar)
print("Minimum value:", ar.min())
print("Maximum value:", ar.max())

[[0.51 0.05 0.53 0.94 0.63 0.62 0.76 0.57 0.95 0.7 ]
 [0.9  0.48 0.59 0.92 0.55 0.54 0.74 0.1  0.76 0.14]
 [0.39 0.73 0.56 0.63 0.14 0.39 0.95 0.18 0.08 0.63]
 [0.71 0.7  0.46 0.89 0.84 0.47 0.36 0.08 0.32 0.25]
 [0.43 0.21 0.93 0.11 0.33 0.87 1.   0.02 0.21 0.92]
 [0.14 0.23 0.72 0.05 0.52 0.9  0.93 0.51 0.26 0.74]
 [0.87 0.29 0.93 0.89 0.81 0.58 0.11 0.91 0.55 0.83]
 [0.56 0.14 0.64 0.48 0.78 0.34 0.9  0.43 0.92 0.36]
 [0.88 0.16 0.84 0.9  0.36 0.77 0.5  0.6  0.94 0.13]
 [0.08 0.74 0.93 0.75 0.83 0.01 0.5  0.59 0.81 0.53]]
Minimum value: 0.01
Maximum value: 1.0


In [17]:
import numpy as np
arr1 = np.random.rand(3,3,3)
print(arr1)

[[[0.35464414 0.71530604 0.08494171]
  [0.85339438 0.54974983 0.40499888]
  [0.69794384 0.67647775 0.26320787]]

 [[0.05378355 0.30690547 0.45370658]
  [0.53077973 0.85337676 0.18452539]
  [0.15695163 0.08188725 0.45860934]]

 [[0.39196543 0.0064249  0.35854677]
  [0.63735969 0.60417699 0.40879819]
  [0.5474168  0.8807474  0.77411836]]]
